# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSecuritytc5():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_securitytc5(self):
    # Test name: security_tc5
    # Step # | name | target | value
    # 1 | open | https://e-learning.hcmut.edu.vn/ | 
    self.driver.get("https://e-learning.hcmut.edu.vn/")
    # 2 | clickAt | linkText=Log in | 
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    # 3 | clickAt | linkText=Teachers and Students of HCMUT | 
    self.driver.find_element(By.LINK_TEXT, "Teachers and Students of HCMUT").click()
    # 4 | type | id=username | nguyen.ngoquang222
    self.driver.find_element(By.ID, "username").send_keys("nguyen.ngoquang222")
    # 5 | type | id=password | 123456789
    self.driver.find_element(By.ID, "password").send_keys("123456789")
    # 6 | clickAt | name=submit | 
    self.driver.find_element(By.NAME, "submit").click()
  
