# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCompatibility():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_c001(self):
    self.driver.get("https://e-learning.hcmut.edu.vn/")
    self.driver.set_window_size(1722, 1034)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.LINK_TEXT, "Teachers and Students of HCMUT").click()
    self.driver.find_element(By.ID, "username").send_keys("trung.bui2405")
    self.driver.find_element(By.ID, "password").send_keys("abcxyz")
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.NAME, "submit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fa-comment-o").click()
    element = self.driver.find_element(By.ID, "message-drawer-toggle-639d88355b122639d8835547b15")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".fa-bell-o").click()
    self.driver.find_element(By.CSS_SELECTOR, ".nav-item:nth-child(3) > .nav-link").click()
    self.driver.find_element(By.CSS_SELECTOR, "ul:nth-child(2) > .list-group-item:nth-child(1) .aalink").click()
    self.driver.find_element(By.ID, "user-menu-toggle").click()
    self.driver.find_element(By.LINK_TEXT, "Thoát ra").click()
  
