# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCalendar():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_uC001(self):
    self.driver.get("https://e-learning.hcmut.edu.vn/")
    self.driver.set_window_size(1722, 1034)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.LINK_TEXT, "Teachers and Students of HCMUT").click()
    self.driver.find_element(By.ID, "username").send_keys("trung.bui2405")
    self.driver.find_element(By.ID, "password").send_keys("abcxyz")
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.NAME, "submit").click()
    self.driver.find_element(By.CSS_SELECTOR, "#moremenu-639d8623b800e-navbar-nav > .nav-item:nth-child(2) > .nav-link").click()
    self.driver.find_element(By.LINK_TEXT, "Full calendar").click()
    self.driver.find_element(By.CSS_SELECTOR, ".float-sm-right").click()
    self.driver.find_element(By.ID, "id_name").click()
    self.driver.find_element(By.ID, "id_name").send_keys("UC-001")
    self.driver.find_element(By.ID, "yui_3_17_2_1_1671267893129_759").click()
  
  def test_uC002(self):
    self.driver.get("https://e-learning.hcmut.edu.vn/")
    self.driver.set_window_size(1722, 1034)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.LINK_TEXT, "Teachers and Students of HCMUT").click()
    self.driver.find_element(By.ID, "username").send_keys("trung.bui2405")
    self.driver.find_element(By.ID, "password").send_keys("abcxyz")
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.NAME, "submit").click()
    self.driver.find_element(By.CSS_SELECTOR, "#moremenu-639d8732a1918-navbar-nav > .nav-item:nth-child(2) > .nav-link").click()
    self.driver.find_element(By.LINK_TEXT, "Full calendar").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) > .day:nth-child(7) li:nth-child(1) .eventname").click()
    self.driver.find_element(By.LINK_TEXT, "Làm bài kiểm tra ngay bây giờ").click()
  
